# Generated by Django 4.0.5 on 2022-06-17 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
