# Generated by Django 4.0.5 on 2022-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_date_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Published_date',
            field=models.TimeField(),
        ),
    ]
