# Generated by Django 4.0.5 on 2022-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
